apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  drink: {{ .Values.favorite.drink | default "not ordered" }}
  dessert: {{ .Values.favorite.dessert | default "not ordered" }}
